#nohup python -u k0_dict_write.py [recordpath] [sample_name] > output.log &
#nohup python -u k0_dict_write.py '/data/anne/timsTOF/hash_records/' 'A1_1_2042' > output.log &

from __future__ import division                                                                                                                                                                                                                                      
from __future__ import print_function                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
import pickle                                                                                                                                                                                                                                                        
import numpy as np                                                                                                                                                                                                                                                   
from collections import deque                                                                                                                                                                                                                                        
from collections import defaultdict                                                                                                                                                                                                                                  
import copy                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                            
import bisect                                                                                                                                                                                                                                                        
#import gc                                                                                                                                                                                                                                                           
import gzip                                                                                                                                                                                                                                                          
from operator import itemgetter                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                     
recordpath=sys.argv[1]
sample_name=sys.argv[2]

isotope_gap=np.zeros((10))                                                                                                                                                                                                                                           
isotope_gap[0]=0.00001                                                                                                                                                                                                                                               
isotope_gap[1]=1.00000                                                                                                                                                                                                                                               
isotope_gap[2]=0.50000                                                                                                                                                                                                                                               
isotope_gap[3]=0.33333                                                                                                                                                                                                                                               
isotope_gap[4]=0.25000                                                                                                                                                                                                                                               
isotope_gap[5]=0.20000                                                                                                                                                                                                                                               
isotope_gap[6]=0.16667                                                                                                                                                                                                                                               
isotope_gap[7]=0.14286                                                                                                                                                                                                                                               
isotope_gap[8]=0.12500                                                                                                                                                                                                                                               
isotope_gap[9]=0.11111                                                                                                                                                                                                                                               
max_part=12                                                                                                                                                                                                                                                          
RT_window=10                                                                                                                                                                                                                                                         
mz_resolution=5 #                                                                                                                                                                                                                                                    
k0_resolution=5                                                                                                                                                                                                                                                      
total_class=10                                                                                                                                                                                                                                                       
RT_unit=0.01                                                                                                                                                                                                                                                         
mz_unit=0.00001                                                                                                                                                                                                                                                      
num_class=10                                                                                                                                                                                                                                                         
new_mz_resolution=3                                                                                                                                                                                                                                                  
new_mz_unit=0.001                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
################################################################################################                                                                                                                                                                     
RT_index=dict()                                                                                                                                                                                                                                                  
for part in range (1, max_part+1):                                                                                                                                                                                                                               
    print(part)                                                                                                                                                                                                                                                  
    f=gzip.open(recordpath+sample_name+'_RT_index_part'+str(part), 'rb')                                                                                                                                                      
    RT_index_temp=pickle.load(f)                                                                                                                                                                                                                                 
    f.close()                                                                                                                                                                                                                                                    
    RT_index.update(RT_index_temp)                                                                                                                                                                                                                               
                                                                                                                                                                                                                                       
print('read done')                                                                                                                                                                                                                                               
k0_dict=dict()                                                                                                                                                                                                                                                   
RT_list=sorted(RT_index.keys())                                                                                                                                                                                                                                  
for rt in RT_list:                                                                                                                                                                                                                                               
    mz_list=sorted(RT_index[rt].keys())                                                                                                                                                                                                                          
    for mz in mz_list:                                                                                                                                                                                                                                           
        k0_list=sorted(RT_index[rt][mz].keys())                                                                                                                                                                                                                  
        for k0 in k0_list:                                                                                                                                                                                                                                       
            k0_dict[k0]=''                                                                                                                                                                                                                                       

k0_list=sorted(k0_dict.keys())                                                                                                                                                                                                                                   
k0_dict=dict()                                                                                                                                                                                                                                                   
for i in range (0, len(k0_list)):                                                                                                                                                                                                                                
    if i%1==0:                                                                                                                                                                                                                                                   
        k0_dict[k0_list[i]]=''                                                                                                                                                                                                                                   

f=gzip.open(recordpath+'pointCloud_'+sample_name+'_k0_dict', 'wb')                                                                                                                                                                            
pickle.dump(k0_dict, f, protocol=3)                                                                                                                                                                                                                              
f.close()
